name: futebol
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - abseil-cpp=20211102.0
  - arrow-cpp=8.0.0
  - asttokens=2.0.5
  - attrs=22.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - blas=2.116
  - blas-devel=3.9.0
  - boost-cpp=1.70.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cycler=0.11.0
  - daal4py=2023.0.2
  - dal=2023.0.1
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.1
  - executing=0.8.3
  - expat=2.2.10
  - fontconfig=2.14.1
  - fonttools=4.39.2
  - freetype=2.10.4
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.6.0
  - grpc-cpp=1.46.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - iniconfig=2.0.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=5.2.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.15
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcurl=7.87.0
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm10=10.0.1
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxgboost=1.7.3
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mpi=1.0
  - mpich=3.3.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.0
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openblas=0.3.21
  - openpyxl=3.0.10
  - openssl=1.1.1t
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - polars=0.16.14
  - pooch=1.7.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=1.7.3
  - pyarrow=8.0.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.1.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - pytest=7.2.2
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2023.2
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.2
  - scikit-learn=1.2.2
  - scikit-learn-intelex=2023.0.2
  - scipy=1.10.0
  - seaborn=0.11.2
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.1
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - tbb=2021.8.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - tzdata=2022g
  - urllib3=1.26.15
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xgboost=1.7.3
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - lxml==4.9.2
      - matplotsoccer==0.0.8
      - mplsoccer==1.1.11
      - mypy-extensions==1.0.0
      - pandera==0.13.4
      - pydantic==1.10.7
      - socceraction==1.4.0
      - typing-extensions==4.5.0
      - typing-inspect==0.8.0
      - wrapt==1.15.0
